#=====================================
#
# NKD - A simple Jekyll boilerplate
#
# More on Jekyll: http://jekyllrb.com/
#
#=====================================

# This will be the first part of the title tag for your site
# <title> {{site.name}} </title>
# ============================================================
name: "NKD - Boilerplate for HTML5/SCSS projects."

# Populates the meta description for the site. Should be under 150 characters for best SEO results.
# ============================================================
description: "NKD - Boilerplate for responsive HTML5/SCSS jekyll projects."

# Owner (organization or individual) of site content - You'll want to change this from mrmrs :)
# ============================================================
author: "mrmrs"

# Change this to your production URL
# ============================================================
url: "http://nkd.cc"

# Publish future posts or not option.
# ============================================================
future: true

# "A list of directories (including trailing slash) and files to exclude from the conversion"
# I normally exclude _sass, README*, and .gitignore
# Directories that start with an underscore _ are not copied over by default. Still like to include _sass anyways.
# ============================================================
exclude: [README.md, Rakefile]

# Pagination variable for how many posts to show in a list
# ============================================================
#paginate: 5

# Style of permalinks
# ============================================================
permalink: pretty

# Variable format options for URL styles below
# ============================================================
# pretty                                          => /2009/04/29/slap-chop/index.html
# /:month-:day-:year/:title.html/                 => 04-29-2009/slap-chop.html
# /blog/:year/:month/:day/:title                  => /blog/2009/04/29/slap-chop/index.html

# Uncomment if you have pygments installed. Used for code syntax highlighting.
# If you're not doing syntax highlighting you can delete this.
#pygments: true
